version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/boxtrack
      - SECRET_KEY=your-super-secret-key-change-in-production
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - boxtrack-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boxtrack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - boxtrack-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@boxtrack.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - boxtrack-network
    restart: unless-stopped

networks:
  boxtrack-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: 